doskey ls=dir $*
doskey rm=del $*
doskey cp=copy $*
doskey mv=ren $*
doskey vi=nvim $*
doskey vim=nvim $*
doskey v=nvim $*
doskey n=nvim $*
doskey g=nvim-qt $*
doskey gv=nvim-qt $*
doskey gvim=nvim-qt $*
doskey ..=cd..
doskey ...=cd..^&^&cd..
doskey ....=cd..^&^&cd..^&^&cd..
doskey .....=cd..^&^&cd..^&^&cd..^&^&cd..
doskey ......=cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..
doskey .......=cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..
doskey ........=cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..
doskey cdh=cd%homepath%
