set PATH=c:\Users\40007688\.fzf\bin;D:\cmder\vendor\git-for-windows\cmd\;%PATH%
set PATH=D:\neovim\bin;D:\Python38;D:\ctags;%PATH%
doskey ls=dir $*
doskey rm=del $*
doskey cp=copy $*
doskey mv=ren $*
doskey vi=nvim $*
doskey vim=nvim $*
doskey v=nvim $*
doskey n=nvim $*
doskey g=nvim-qt $*
doskey gv=nvim-qt $*
doskey gvim=nvim-qt $*
doskey ..=cd..
doskey ...=cd..^&^&cd..
doskey ....=cd..^&^&cd..^&^&cd..
doskey .....=cd..^&^&cd..^&^&cd..^&^&cd..
doskey ......=cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..
doskey .......=cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..
doskey ........=cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..^&^&cd..
doskey cdh=cd%homepath%
